name: Linting and style checking

on: [pull_request,push]

jobs:
  luacheck:
    name: Luacheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Prepare
        run: |
          if grep -q "fail" test.txt; then
            echo "Error: File contains the string 'fail'"
            exit
          fi
